# Generated by Django 2.2.7 on 2019-11-26 10:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DownloadCount', models.IntegerField(default=0)),
                ('Datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('FilePath', models.CharField(max_length=32)),
                ('FileName', models.CharField(default='', max_length=32)),
                ('FileSize', models.CharField(max_length=10)),
                ('File', models.FileField(upload_to='.storage')),
                ('UploadUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FileShare',
            },
        ),
    ]
