# Generated by Django 2.2.7 on 2019-11-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileShare', '0002_remove_fileupload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='DownloadCount',
        ),
    ]
