# Generated by Django 2.2.7 on 2019-12-25 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key='True', related_name='companyUser', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Avatar', models.CharField(blank=True, max_length=150)),
                ('City', models.CharField(default='', max_length=8)),
                ('Address', models.CharField(max_length=50)),
                ('Intro', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartTimeUser',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key='True', related_name='partTimeUser', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Avatar', models.CharField(blank=True, max_length=150)),
                ('PhoneNumber', models.CharField(default='', max_length=11)),
                ('City', models.CharField(max_length=8)),
                ('Intro', models.TextField(blank=True)),
                ('Hired', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobName', models.CharField(max_length=20)),
                ('JobCity', models.CharField(default='', max_length=8)),
                ('JobLoc', models.CharField(max_length=50)),
                ('JobSalary', models.IntegerField()),
                ('JobWorkTime', models.CharField(max_length=20)),
                ('JobDetail', models.TextField()),
                ('BelongtoCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartTimePlatform.CompanyUser')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BelongtoJob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartTimePlatform.Jobs')),
                ('BelongtoUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartTimePlatform.PartTimeUser')),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BelongtoCompany', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PartTimePlatform.CompanyUser')),
                ('BelongtoJob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartTimePlatform.Jobs')),
                ('CandidateUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartTimePlatform.PartTimeUser')),
            ],
        ),
    ]
