# Generated by Django 2.2.7 on 2019-12-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartTimePlatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='JobName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='favoritejobs',
            name='JobName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
