# Generated by Django 2.2.7 on 2019-12-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartTimePlatform', '0002_auto_20191227_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='Companyname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='parttimeuser',
            name='Username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
