# Generated by Django 2.2.7 on 2019-12-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartTimePlatform', '0003_auto_20191227_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='CandidateName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
