# Generated by Django 2.2.7 on 2020-01-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartTimePlatform', '0004_candidates_candidatename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='Address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='parttimeuser',
            name='City',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
