# Generated by Django 2.2.7 on 2020-01-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartTimePlatform', '0005_auto_20200102_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='isHire',
            field=models.BooleanField(default=False),
        ),
    ]
