# Generated by Django 2.2.7 on 2020-01-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartTimePlatform', '0006_jobs_ishire'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='isHire',
            field=models.BooleanField(default=False),
        ),
    ]
