# Generated by Django 2.2.7 on 2020-02-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartTimePlatform', '0009_auto_20200214_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttimeuser',
            name='PhoneNumber',
            field=models.CharField(blank=True, default='', max_length=11, null=True),
        ),
    ]
