# Generated by Django 2.2.7 on 2020-02-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartTimePlatform', '0010_auto_20200214_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttimeuser',
            name='Username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
